title: "Adrien Anthore"
author: "Adrien Anthore"
description: |
  Adrien Anthore,
  PhD student at Observatoire Astronomique de Strasbourg.
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: " "

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
excerpt_separator: "<!--more-->"

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md", title: "About Me"}
  - {title: "CV", url: "https://adnothing.github.io/doc/ANTHORE_CV.pdf"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:adrien.anthore@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/ADnothing"}
  - {title: Linkedin, icon: linkedin, url: "https://fr.linkedin.com/in/adrien-anthore-625152225"}
  - {title: Links, icon: link, url: "https://linktr.ee/lobservatoiredadrien"}
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
